defaultEnvironment: test
#defaultEnvironment: preprod

environments:
  test:
    envName: test
    appUrl: http://146.59.32.4/index.php/
    eTitle: TesterSii
    email: test@test.com
    password: password

  preprod:
    envName: preprod
    appUrl: https://logback.qos.ch/
    eTitle: Logback Home

browser:
  browser: chrome
  browserAttachScreenshot: false
  headlessMode: false
  browserTimeout: 20